language: php
php:
- '7.1'
notifications:
  slack:
    rooms:
      secure: 5bT6B7dx72L5/KFru7M3Wi63OxB2apRj3luazLEKhqCPVuyMLnhk6WiAPfRzgt1MrnnIEkSEBDb1iWuZf6WOQC8w8jmtYTvjQ+qvB/O81SVO8WrQTUIbAmvVIgSXIJVtFloYTJuoow/2T/cuoixZEHp/6Cot8fqTCJXpLI+ZsLqUe/rqwRk+njUHGgxMfvh1AyniDDWxZRyX+XfVR5CtZ4EGImsgdSgPECxQE+VYSeQRhvT3+MiC5vMN9B79O65C67geKIEKI0FF54c8bzjksBTYJBh4iNG0hiuA79XKHPuXIxB98gtQH1L0E5jii1dDuTCWuF1MjZR7i87MEOttor0bIl2avFKiOwLJQYGKo2Pv4QNpsqAVbV3uzgmA3c2DNLjHCF90TxI3dEBwvWRQk6/YFc9n6W+r+n+3GsozI0KCfw5Pv1gP30TBnKPQEaioNOKMP5u/2oioM8yz8MgRlRYRJ3tdjqMIrx9wA2t+lywDwbP+OjV4QShATaettin4DUiod68RE/OtHhaI92YzNBWkdQP4OA17/HdHY0PpGB++H2lopxOKA4tTUnVr3ysu822kpxotfq6/PTQTUZTE7rkl/FjHAuLDnvSWNDAqINc4xoiNmz5w0Ts5L4pfcRGLShyYnXwnXOSXeaOWMISBdx/Zj02q+ciugmMRu2DTkfo=
